### ISSUE TITLE
[Cloudflare Calls] Undocumented API endpoint request fields for creating tracks

### ISSUE THREAD

**Issue by oxcabe** [cloudflare/orange#153]
_I'm opening this issue here since it's where the code with the relevant fields are. Consider moving it to a more appropiate repository if necessary._

The following code creates a track to communicate with the OpenAI Realtime models.
Notice the params used in the `NewTracks` method, especially those with comments on top of them (i.e. `bidirectionalMediaStream` and `kind`):
https://github.com/cloudflare/orange/blob/61608e17f2d368011ccf32ba846ab39bbcf52e54/app/durableObjects/ChatRoom.server.ts#L394-L406

`NewTracks` is defined here. The method sends the `body` argument directly as the request body:

https://github.com/cloudflare/orange/blob/61608e17f2d368011ccf32ba846ab39bbcf52e54/app/utils/openai.server.ts#L44-L57

Developers find the Cloudflare Calls API reference [here](https://developers.cloudflare.com/calls/https-api/), which is where the [OpenAPI schema](https://developers.cloudflare.com/calls/static/calls-api-2024-05-21.yaml) for the endpoint used in `NewTracks` can be found.
 
We can find that the schema for this endpoint is defined as:
```yaml
TracksRequest:
      type: object
      properties:
        sessionDescription:
          $ref: "#/components/schemas/SessionDescription"
        tracks:
          type: array
          items:
            $ref: "#/components/schemas/TrackObject"
```

The `tracks` array is composed of `TrackObject` elements, which looks like:

```yaml
TrackObject:
      type: object
      properties:
        location:
          type: string
          enum:
            - local
            - remote
          description: If you want to share a track, it should be local. If you want to play a track shared by a remote agent, it should be remote
        mid:
          type: string
          description: mid associated to track's transceiver. It should be set with local tracks only
        sessionId:
          type: string
          description: Session ID of the track owner. It should be set for remote tracks only
        trackName:
          type: string
          description: Given name for the track
```

The `TrackObject` schema doesn't reference neither `bidirectionalMediaStream` nor `kind` fields in it. If these parameters do actually change the behavior of the API call (I haven't tested this), it might happen that they're undocumented.

If that's the case, could we have an update for the schema?
